<?php

namespace Aught\SpaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public static function createCommentFromSocketMessage($msg, $space, $author, $em)
    {
        if (!isset($msg['m'])) {
            throw new \Exception("Invalid message contents - missing 'm'!", 1);
        }

        $body = trim($msg['m']);

        if (empty($body)) {
            throw new \Exception("Invalid message - empty message!", 1);
        }

        $comment = new Comment();
        $comment->setSpace($space);
        $comment->setAuthor($author);
        $comment->setBody($body);

        $em->persist($comment);
        $em->flush();

        return $comment;
    }
}
