<?php

namespace Aught\SpaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelishRepository extends EntityRepository
{
    public static function toggleRelish($space, $author, $em, $relish_rep, $set_relish_to = null)
    {
        $existing = $relish_rep->findOneBy(array(
            'space'  => $space,
            'author' => $author
        ));

        if (!$existing && (is_null($set_relish_to) || $set_relish_to === true)) {
            $relish = new Relish();
            $relish->setSpace($space);
            $relish->setAuthor($author);

            $em->persist($relish);
            $em->flush();
        }

        if ($existing && (is_null($set_relish_to) || $set_relish_to === false)) {
            $em->remove($existing);
            $em->flush();
        }
    }
}
